# Generated by Django 3.0.8 on 2020-07-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_auto_20200715_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteConifguration',
            new_name='SiteConfiguration',
        ),
    ]
