# Generated by Django 3.1.2 on 2020-11-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='file',
            field=models.ImageField(upload_to='images/backgrounds/'),
        ),
    ]
