# Generated by Django 3.0.8 on 2020-07-13 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='artist', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
