# Generated by Django 3.0.8 on 2020-07-15 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_auto_20200715_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
    ]
