# Generated by Django 3.0.8 on 2020-07-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_auto_20200714_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='year',
        ),
    ]
