# Generated by Django 3.0.8 on 2020-07-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_remove_song_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default='rock', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.IntegerField(default=1993),
            preserve_default=False,
        ),
    ]
