# Generated by Django 3.0.8 on 2020-07-14 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radio', '0007_auto_20200714_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='music/uploads/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('user_added', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
