# Generated by Django 3.0.8 on 2020-07-15 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radio', '0008_auto_20200714_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='date_added',
            new_name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='track',
            name='user_added',
        ),
        migrations.AddField(
            model_name='track',
            name='user_uploaded',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_uploaded', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
